### ISSUE TITLE
memory leak in stub()

### ISSUE THREAD

**Issue by vsespb** [kingpong/perl-Test-Spec#14]
```
use strict;
use warnings;
use Test::Spec;
use Scalar::Util qw/weaken/;

my $check_leak;

describe "a" => sub {
  it "b" => sub {
    my $x = stub(z => 42);
    $check_leak = $x;
    weaken($check_leak);
  };
};

runtests unless caller;

print "Memory leak\n" if $check_leak;

```
prints "Memory leak"

that makes harder to test that there are no memory leaks in testable code.
I would expect $x freed after `it "b"` execution finished.

**Comment by kingpong** [comment]
I acknowledge this problem but I'm not quite sure what to do about it. I have spent a few hours on it without results. Perhaps someone with more (and less rusty) skills can solve it.

I suspect the problem is that `stub()` and friends attach themselves to the current context, so they can be torn down (and expectations verified) after the example has executed.

I have documented this as a known issue.
